### ISSUE TITLE
Support generation of OpenAI summary

### ISSUE THREAD

**Issue by brennan3** [delphidigital/delphi-tg-bots#35]
## Overview:
Delphi Digital finds interesting content and shares links to it with our customers at:
https://members.delphidigital.io/feed?category=reads

We are interested in generating AI summaries of these shared links so that summaries can be shown directly in our portal. We currently use a Telegram Bot to add these links to our site. We'd like to expand upon the current Telegram Bot (this repo) to support generating the summaries.

## Prerequisites
- You'll need your own OpenAI key while testing locally

## Task
- Add environment variable for OpenAI key
- Write a new function (in a new module within the repo) that calls OpenAI and generates a 500 character or less summary when provided a URL
- Update the current `handleUpdateUrl` function (https://github.com/delphidigital/delphi-tg-bots/blob/main/bots/reads.ts#L429) to get the summary and populate the item description field with it if the URL is not a twitter-esque URL (for twitter, we just store the tweet text as the description)
- If the call fails, fall back to the metadata description already in place on the item, send a message to the user that the AI summary call failed
- Incorporate testing infrastructure to run mocha tests and ensure tests are written for any new functionality added during this task. Note that you do not need to add any tests for any of the pre-existing functions, only around new code that you add.

## Call outs
- You won't be able to publish an item locally. This task is just to ensure the item being generated as the proper description
- If helpful, here is an example of AI summarization on a url: https://github.com/georgeck/SummAIze
- Please include a video with your pull request showcasing your code change functioning as expected and calling out any decisions you may have made while working on the feature. (https://www.loom.com/ is one tool that is great for quickly creating videos, but you can use whatever tool you are most comfortable with)

**Comment by chainparser** [comment]
@brennan3, I'd like to take up this task.

**Comment by brennan3** [comment]
@mawutory 

sounds great - for all the issues in our repo with bounties, the bounties are paid first come first serve (based on acceptable PR being up). Now that you have commented, others can see you are working on this, and perhaps if no PR is up within a few days, someone else might attempt to resolve this. If you have any questions, ping on this ticket and I'll follow up!

**Comment by stocks29** [comment]
@mawutory this bounty is still open if you are interested in working on it. the author of the PR doesn't appear to be working on this anymore.

**Comment by SherbetLemon47** [comment]
Would like to pick this up is nobody is working on this, I would just want to know where do I obtain all the environment variables

**Comment by stocks29** [comment]
Hi @SherbetLemon47, you're good to start working on this as nobody else is. See below for environment variables

`DELPHI_READS_API_KEY` - just put in a random value for this. you won't be able to post items but that is not required for this task. the app just requires a value to startup with `npm run start:dev`.

For `DELPHI_READS_WEBHOOK_URL` follow the [local development readme instructions](https://github.com/delphidigital/delphi-tg-bots?tab=readme-ov-file#local-development) for smee. the generated value should be of the form: `https://smee.io/YOUR-TOKEN-HERE`

For `DELPHI_READS_BOT_TOKEN` you'll need to create a test bot with Telegrams [botfather](https://core.telegram.org/bots/tutorial).

For `OPENAI_API_KEY` you'll need to generate an OpenAI API token in your OpenAI account.

The other env vars can be set to these exact values:
```
DELPHI_API_BASE_URL=https://members.delphidigital.io
DELPHI_READS_READING_LIST_ID=9
```

There is already a [PR](https://github.com/delphidigital/delphi-tg-bots/pull/40) up, but it requires some changes and testing. Feel free to use this as a starting point if you think it'd be useful. You're welcome to start from scratch if you prefer too.

Don't hesitate to reach out with any additional questions.

**Comment by SherbetLemon47** [comment]
Put up a PR. For some reason couldn't get fetchapi to work with getting the html content. So settled with axios. Hope thats okay.

**Comment by stocks29** [comment]
@SherbetLemon47 thanks for submitting the PR! I'll be looking this over today.
